services:
  - type: web
    name: game-node
    env: node
    buildCommand: cd game-starter && npm install && npm run build
    startCommand: cd game-starter && npm start
    envVars:
      - key: NODE_ENV
        value: production      - key: PORT
        value: 10000    autoDeploy: true